---
name: PackageFedora

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: srcml/fedora:41
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      # - name: Setup packages
      #   shell: bash
      #   run :
      #     apt-get install ninja-build

      - name: CMake Setup
        working-directory: build
        shell: bash
        run: |
          cmake --version
          cmake .. -G Ninja

      - name: Build
        working-directory: build
        shell: bash
        run: |
          cmake --build . --config Release --target all
          # ninja
      - uses: actions/upload-artifact@v4
        with:
          name: Executable
          path: |
            build/srccomplexity

      - name: Install
        working-directory: build
        shell: bash
        run: |
          cmake --build . --config Release --target install/strip

      - name: Run
        working-directory: build
        shell: bash
        run: |
          srccomplexity < ../srcMLXPathCount.cpp.xml

      - name: Install srcml
        working-directory: build
        shell: bash
        run: |
          curl -L -O https://mlcollard.net/dist/srcml-1.0.0-1.fc38.x86_64.rpm
          dnf install -y srcml-1.0.0-1.fc38.x86_64.rpm

      - name: Test
        working-directory: build
        continue-on-error: true
        shell: bash
        run: |
          ctest --verbose | tee TestResults.log
      - uses: actions/upload-artifact@v4
        with:
          name: Test.log
          path: |
            build/Testing/Temporary/LastTest.log
            build/TestResults.log
